package sys.model;

import java.util.Date;

public class Serverinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.cpuUsage
     *
     * @mbggenerated
     */
    private String cpuusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.setCpuUsage
     *
     * @mbggenerated
     */
    private String setcpuusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.jvmUsage
     *
     * @mbggenerated
     */
    private String jvmusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.setJvmUsage
     *
     * @mbggenerated
     */
    private String setjvmusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.ramUsage
     *
     * @mbggenerated
     */
    private String ramusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.setRamUsage
     *
     * @mbggenerated
     */
    private String setramusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.operTime
     *
     * @mbggenerated
     */
    private Date opertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serverinfo.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverinfo
     *
     * @mbggenerated
     */
    public Serverinfo(Integer id, String cpuusage, String setcpuusage, String jvmusage, String setjvmusage, String ramusage, String setramusage, String email, Date opertime, String mark) {
        this.id = id;
        this.cpuusage = cpuusage;
        this.setcpuusage = setcpuusage;
        this.jvmusage = jvmusage;
        this.setjvmusage = setjvmusage;
        this.ramusage = ramusage;
        this.setramusage = setramusage;
        this.email = email;
        this.opertime = opertime;
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.id
     *
     * @return the value of serverinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.cpuUsage
     *
     * @return the value of serverinfo.cpuUsage
     *
     * @mbggenerated
     */
    public String getCpuusage() {
        return cpuusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.setCpuUsage
     *
     * @return the value of serverinfo.setCpuUsage
     *
     * @mbggenerated
     */
    public String getSetcpuusage() {
        return setcpuusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.jvmUsage
     *
     * @return the value of serverinfo.jvmUsage
     *
     * @mbggenerated
     */
    public String getJvmusage() {
        return jvmusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.setJvmUsage
     *
     * @return the value of serverinfo.setJvmUsage
     *
     * @mbggenerated
     */
    public String getSetjvmusage() {
        return setjvmusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.ramUsage
     *
     * @return the value of serverinfo.ramUsage
     *
     * @mbggenerated
     */
    public String getRamusage() {
        return ramusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.setRamUsage
     *
     * @return the value of serverinfo.setRamUsage
     *
     * @mbggenerated
     */
    public String getSetramusage() {
        return setramusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.email
     *
     * @return the value of serverinfo.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.operTime
     *
     * @return the value of serverinfo.operTime
     *
     * @mbggenerated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serverinfo.mark
     *
     * @return the value of serverinfo.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }
}